# Workflow to deploy demo environment
name: 'Terraform - Apply DEV'

#The workflow will be triggered when a pull request is merged into the main branch.
#To maintain the integrity and security of the infrastructure, manual executions are not allowed.
on:
  push:
    branches:
      - development

jobs:
  apply_dev:
    runs-on: ubuntu-latest
    name: Terraform apply for DEV environment
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
        terraform_version: 1.5.2

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./environments/dev
      env:
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      continue-on-error: false

    - name: Terraform Apply
      id: plan
      run: terraform apply -auto-approve
      working-directory: ./environments/dev
      env:
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      continue-on-error: false